erDiagram
    USERS ||--o{ AFFILIATIONS : user_id
    CAMPUSES ||--o{ COURSES : campus_id
    CAMPUSES ||--o{ AFFILIATIONS : campus_id
    COURSES o|--o{ AFFILIATIONS : course_id

    USERS {
        bigint id PK
        varchar name
        varchar email UK
        varchar password
        timestamp created_at
    }
    CAMPUSES {
        bigint id PK
        varchar name
        bigint address_id FK
        timestamp deactivated_at
    }
    COURSES {
        bigint id PK
        bigint campus_id FK
        varchar name
        bigint coordinator_affiliation_id FK
        timestamp deactivated_at
    }
    AFFILIATIONS {
        bigint id PK
        bigint user_id FK
        bigint campus_id FK
        bigint course_id FK
        varchar type
        varchar registration_number
        timestamp deactivated_at
    }
